services:
  postgres-syncstudy:
    image: postgres:latest
    container_name: postgres-syncstudy
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - PGDATABASE=syncstudy
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - syncstudy_vol:/var/lib/postgresql/data
    networks:
      - syncstudy_net

volumes:
  syncstudy_vol:

networks:
  syncstudy_net: